--
-- PostgreSQL database dump
--

\restrict M81NlIvLdtCz8Fwcknivpv3e2GhvuskUIkPxqQww1Jg69d4sgBtdV4m3zHDWtxq

-- Dumped from database version 15.18 (Debian 15.18-1.pgdg13+1)
-- Dumped by pg_dump version 15.18 (Debian 15.18-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public."Packages" DROP CONSTRAINT IF EXISTS "FK_Packages_Transports_TransportId";
ALTER TABLE IF EXISTS ONLY public."Packages" DROP CONSTRAINT IF EXISTS "FK_Packages_Terminals_OriginTerminalId";
ALTER TABLE IF EXISTS ONLY public."Packages" DROP CONSTRAINT IF EXISTS "FK_Packages_Terminals_DestinationTerminalId";
ALTER TABLE IF EXISTS ONLY public."Packages" DROP CONSTRAINT IF EXISTS "FK_Packages_AspNetUsers_SenderUserId";
ALTER TABLE IF EXISTS ONLY public."Packages" DROP CONSTRAINT IF EXISTS "FK_Packages_AspNetUsers_RecipientUserId";
ALTER TABLE IF EXISTS ONLY public."AspNetUserTokens" DROP CONSTRAINT IF EXISTS "FK_AspNetUserTokens_AspNetUsers_UserId";
ALTER TABLE IF EXISTS ONLY public."AspNetUserRoles" DROP CONSTRAINT IF EXISTS "FK_AspNetUserRoles_AspNetUsers_UserId";
ALTER TABLE IF EXISTS ONLY public."AspNetUserRoles" DROP CONSTRAINT IF EXISTS "FK_AspNetUserRoles_AspNetRoles_RoleId";
ALTER TABLE IF EXISTS ONLY public."AspNetUserLogins" DROP CONSTRAINT IF EXISTS "FK_AspNetUserLogins_AspNetUsers_UserId";
ALTER TABLE IF EXISTS ONLY public."AspNetUserClaims" DROP CONSTRAINT IF EXISTS "FK_AspNetUserClaims_AspNetUsers_UserId";
ALTER TABLE IF EXISTS ONLY public."AspNetRoleClaims" DROP CONSTRAINT IF EXISTS "FK_AspNetRoleClaims_AspNetRoles_RoleId";
DROP INDEX IF EXISTS public."UserNameIndex";
DROP INDEX IF EXISTS public."RoleNameIndex";
DROP INDEX IF EXISTS public."IX_Packages_TransportId";
DROP INDEX IF EXISTS public."IX_Packages_TrackingNumber";
DROP INDEX IF EXISTS public."IX_Packages_Status";
DROP INDEX IF EXISTS public."IX_Packages_SenderUserId";
DROP INDEX IF EXISTS public."IX_Packages_RecipientUserId";
DROP INDEX IF EXISTS public."IX_Packages_OriginTerminalId";
DROP INDEX IF EXISTS public."IX_Packages_DestinationTerminalId";
DROP INDEX IF EXISTS public."IX_AspNetUserRoles_RoleId";
DROP INDEX IF EXISTS public."IX_AspNetUserLogins_UserId";
DROP INDEX IF EXISTS public."IX_AspNetUserClaims_UserId";
DROP INDEX IF EXISTS public."IX_AspNetRoleClaims_RoleId";
DROP INDEX IF EXISTS public."EmailIndex";
ALTER TABLE IF EXISTS ONLY public."__EFMigrationsHistory" DROP CONSTRAINT IF EXISTS "PK___EFMigrationsHistory";
ALTER TABLE IF EXISTS ONLY public."Transports" DROP CONSTRAINT IF EXISTS "PK_Transports";
ALTER TABLE IF EXISTS ONLY public."Terminals" DROP CONSTRAINT IF EXISTS "PK_Terminals";
ALTER TABLE IF EXISTS ONLY public."Packages" DROP CONSTRAINT IF EXISTS "PK_Packages";
ALTER TABLE IF EXISTS ONLY public."AspNetUsers" DROP CONSTRAINT IF EXISTS "PK_AspNetUsers";
ALTER TABLE IF EXISTS ONLY public."AspNetUserTokens" DROP CONSTRAINT IF EXISTS "PK_AspNetUserTokens";
ALTER TABLE IF EXISTS ONLY public."AspNetUserRoles" DROP CONSTRAINT IF EXISTS "PK_AspNetUserRoles";
ALTER TABLE IF EXISTS ONLY public."AspNetUserLogins" DROP CONSTRAINT IF EXISTS "PK_AspNetUserLogins";
ALTER TABLE IF EXISTS ONLY public."AspNetUserClaims" DROP CONSTRAINT IF EXISTS "PK_AspNetUserClaims";
ALTER TABLE IF EXISTS ONLY public."AspNetRoles" DROP CONSTRAINT IF EXISTS "PK_AspNetRoles";
ALTER TABLE IF EXISTS ONLY public."AspNetRoleClaims" DROP CONSTRAINT IF EXISTS "PK_AspNetRoleClaims";
DROP TABLE IF EXISTS public."__EFMigrationsHistory";
DROP TABLE IF EXISTS public."Transports";
DROP TABLE IF EXISTS public."Terminals";
DROP TABLE IF EXISTS public."Packages";
DROP TABLE IF EXISTS public."AspNetUsers";
DROP TABLE IF EXISTS public."AspNetUserTokens";
DROP TABLE IF EXISTS public."AspNetUserRoles";
DROP TABLE IF EXISTS public."AspNetUserLogins";
DROP TABLE IF EXISTS public."AspNetUserClaims";
DROP TABLE IF EXISTS public."AspNetRoles";
DROP TABLE IF EXISTS public."AspNetRoleClaims";
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


--
-- Name: Packages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Packages" (
    "Id" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Weight" double precision NOT NULL,
    "TrackingNumber" character varying(64) NOT NULL,
    "SenderUserId" text NOT NULL,
    "RecipientUserId" text NOT NULL,
    "OriginTerminalId" integer NOT NULL,
    "DestinationTerminalId" integer NOT NULL,
    "TransportId" integer,
    "Status" character varying(32) NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    "DeliveredAt" timestamp with time zone
);


--
-- Name: Packages_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Packages" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Packages_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Terminals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Terminals" (
    "Id" integer NOT NULL,
    "Number" text NOT NULL,
    "Address" text NOT NULL
);


--
-- Name: Terminals_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Terminals" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Terminals_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Transports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Transports" (
    "Id" integer NOT NULL,
    "Type" text NOT NULL,
    "Status" integer NOT NULL
);


--
-- Name: Transports_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Transports" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Transports_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AspNetRoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
6a0ef3d3-555d-42a8-8538-010e9107ba7c	Admin	ADMIN	\N
9f6481ea-35c8-4534-92ab-7a8846d18b1a	User	USER	\N
\.


--
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AspNetUserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AspNetUserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AspNetUserRoles" ("UserId", "RoleId") FROM stdin;
7046a86f-06ca-49ed-8121-699a6fe02986	6a0ef3d3-555d-42a8-8538-010e9107ba7c
\.


--
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AspNetUserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AspNetUsers" ("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
80b04b76-5966-4e8a-a395-eb8dd39cb236	dima@gmail.com	DIMA@GMAIL.COM	dima@gmail.com	DIMA@GMAIL.COM	f	AQAAAAIAAYagAAAAEB2Ro1M4YzyN/I6Ou+sUJvZcv9MnE/4zhO6/8+ueuNnkmFcRg6WEO1iHudSETE6PJA==	S5WVC3C4E2YBW2KGRPD6FI2NA2OAJV3K	67d39b8e-5d44-487b-b4bd-255903433c79	\N	f	f	\N	t	0
0ab5755a-378d-4463-90e0-741f0c50bfce	kris@gmail.com	KRIS@GMAIL.COM	kris@gmail.com	KRIS@GMAIL.COM	f	AQAAAAIAAYagAAAAEEtsHqUGz6iNXGZmKFEJl5qeP4b6OpJlpKor86JYbHswDSBizydTd18DTlGCjbmkEw==	7L3INQ6EZZBKRATD5QGJJIWQDY6P4KFV	15aeecc1-bc86-4db4-b3ce-8df2350fcadc	\N	f	f	\N	t	0
7046a86f-06ca-49ed-8121-699a6fe02986	admin@gmail.com	ADMIN@GMAIL.COM	admin@gmail.com	ADMIN@GMAIL.COM	t	AQAAAAIAAYagAAAAEHgT82nMKCJ8kvsWa8VFlh178W9by8GizVB4ZRGtV0hVZW7zPE4BOzd/6X94POzLdQ==	UZK5ECY3FNZNY4DBVWGDQAYR4AUOOJJF	22aec74b-0df4-474d-9acc-5af34c8d7834	\N	f	f	\N	t	0
\.


--
-- Data for Name: Packages; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Packages" ("Id", "Name", "Weight", "TrackingNumber", "SenderUserId", "RecipientUserId", "OriginTerminalId", "DestinationTerminalId", "TransportId", "Status", "SentAt", "DeliveredAt") FROM stdin;
1	cat	2	PKG f0511113e31d49f68842214fe6c64111	0ab5755a-378d-4463-90e0-741f0c50bfce	80b04b76-5966-4e8a-a395-eb8dd39cb236	1	2	1	Received	2026-05-18 14:14:08.425272+00	\N
2	tea	1	PKG 5e17e0d8133149768a0c0a45a84418e7	0ab5755a-378d-4463-90e0-741f0c50bfce	80b04b76-5966-4e8a-a395-eb8dd39cb236	1	2	1	Received	2026-05-18 14:14:26.673624+00	\N
3	bananas	4	PKG 8f68ff80985648c29ddee28b67f70351	80b04b76-5966-4e8a-a395-eb8dd39cb236	0ab5755a-378d-4463-90e0-741f0c50bfce	1	2	1	InTransit	2026-05-18 19:04:11.320904+00	\N
6	Plants	2	PKG e7db6900973741a3837b7bdb46447517	80b04b76-5966-4e8a-a395-eb8dd39cb236	0ab5755a-378d-4463-90e0-741f0c50bfce	1	2	2	InTransit	2026-05-19 14:28:40.906168+00	\N
5	TV	8	PKG afe67a8b5a7c4d0a85c7447e28866bd3	80b04b76-5966-4e8a-a395-eb8dd39cb236	0ab5755a-378d-4463-90e0-741f0c50bfce	1	2	4	InTransit	2026-05-19 14:28:29.436502+00	\N
8	Hamburgers	2	PKG 24a468b64eb34e63b514434195d5216e	7046a86f-06ca-49ed-8121-699a6fe02986	0ab5755a-378d-4463-90e0-741f0c50bfce	1	2	6	Received	2026-05-19 14:31:16.82838+00	2026-05-19 15:24:47.524233+00
4	computer	5	PKG eddff54f49124b7e8af58847f1f2ac5d	80b04b76-5966-4e8a-a395-eb8dd39cb236	0ab5755a-378d-4463-90e0-741f0c50bfce	1	2	3	Delivered	2026-05-19 14:28:19.186722+00	2026-05-19 16:11:51.73107+00
10	test1	3	PKG c8af70c54a634af0a050250363e5c063	7046a86f-06ca-49ed-8121-699a6fe02986	80b04b76-5966-4e8a-a395-eb8dd39cb236	1	2	3	InTransit	2026-05-19 16:10:03.085092+00	\N
9	Car parts	15	PKG da9a2700e64f4e0f973e98c55f6f6ec3	7046a86f-06ca-49ed-8121-699a6fe02986	0ab5755a-378d-4463-90e0-741f0c50bfce	1	2	6	Delivered	2026-05-19 14:31:58.58028+00	2026-05-19 16:13:18.709565+00
11	test2	3	PKG 4e2dfe167b7743f58ef29122708ceedc	7046a86f-06ca-49ed-8121-699a6fe02986	80b04b76-5966-4e8a-a395-eb8dd39cb236	1	2	6	InTransit	2026-05-19 16:10:08.048853+00	\N
7	Coffee	2	PKG 7619e83d7c8a4a5b81e35a304164508d	7046a86f-06ca-49ed-8121-699a6fe02986	0ab5755a-378d-4463-90e0-741f0c50bfce	1	2	5	Delivered	2026-05-19 14:31:08.550975+00	2026-05-19 16:40:00.015135+00
12	test4	3	PKG 5e59b0517caa46468e0e4dc3343250fc	7046a86f-06ca-49ed-8121-699a6fe02986	80b04b76-5966-4e8a-a395-eb8dd39cb236	1	2	\N	WaitingForTransport	2026-05-19 16:40:55.408034+00	\N
\.


--
-- Data for Name: Terminals; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Terminals" ("Id", "Number", "Address") FROM stdin;
1	1	Kyiv
2	2	Lviv
\.


--
-- Data for Name: Transports; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Transports" ("Id", "Type", "Status") FROM stdin;
1	Truck_1	2
2	Truck_2	2
4	string	2
3	string	2
6	Train_1	2
5	truck_4	3
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260427123530_InitialCreate	8.0.22
\.


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- Name: Packages_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Packages_Id_seq"', 12, true);


--
-- Name: Terminals_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Terminals_Id_seq"', 2, true);


--
-- Name: Transports_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Transports_Id_seq"', 6, true);


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: Packages PK_Packages; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Packages"
    ADD CONSTRAINT "PK_Packages" PRIMARY KEY ("Id");


--
-- Name: Terminals PK_Terminals; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Terminals"
    ADD CONSTRAINT "PK_Terminals" PRIMARY KEY ("Id");


--
-- Name: Transports PK_Transports; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Transports"
    ADD CONSTRAINT "PK_Transports" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_Packages_DestinationTerminalId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Packages_DestinationTerminalId" ON public."Packages" USING btree ("DestinationTerminalId");


--
-- Name: IX_Packages_OriginTerminalId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Packages_OriginTerminalId" ON public."Packages" USING btree ("OriginTerminalId");


--
-- Name: IX_Packages_RecipientUserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Packages_RecipientUserId" ON public."Packages" USING btree ("RecipientUserId");


--
-- Name: IX_Packages_SenderUserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Packages_SenderUserId" ON public."Packages" USING btree ("SenderUserId");


--
-- Name: IX_Packages_Status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Packages_Status" ON public."Packages" USING btree ("Status");


--
-- Name: IX_Packages_TrackingNumber; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Packages_TrackingNumber" ON public."Packages" USING btree ("TrackingNumber");


--
-- Name: IX_Packages_TransportId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Packages_TransportId" ON public."Packages" USING btree ("TransportId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Packages FK_Packages_AspNetUsers_RecipientUserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Packages"
    ADD CONSTRAINT "FK_Packages_AspNetUsers_RecipientUserId" FOREIGN KEY ("RecipientUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Packages FK_Packages_AspNetUsers_SenderUserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Packages"
    ADD CONSTRAINT "FK_Packages_AspNetUsers_SenderUserId" FOREIGN KEY ("SenderUserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Packages FK_Packages_Terminals_DestinationTerminalId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Packages"
    ADD CONSTRAINT "FK_Packages_Terminals_DestinationTerminalId" FOREIGN KEY ("DestinationTerminalId") REFERENCES public."Terminals"("Id") ON DELETE RESTRICT;


--
-- Name: Packages FK_Packages_Terminals_OriginTerminalId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Packages"
    ADD CONSTRAINT "FK_Packages_Terminals_OriginTerminalId" FOREIGN KEY ("OriginTerminalId") REFERENCES public."Terminals"("Id") ON DELETE RESTRICT;


--
-- Name: Packages FK_Packages_Transports_TransportId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Packages"
    ADD CONSTRAINT "FK_Packages_Transports_TransportId" FOREIGN KEY ("TransportId") REFERENCES public."Transports"("Id") ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict M81NlIvLdtCz8Fwcknivpv3e2GhvuskUIkPxqQww1Jg69d4sgBtdV4m3zHDWtxq

